import type {
  ClientRecord,
  DashboardSnapshot,
  LoanRecord,
  ReportsSnapshot,
  SavingsRecord,
  SettingsSnapshot,
  SyncSnapshot,
  TransactionRecord,
} from "@/lib/types";
import { formatCompactNumber, formatCurrency } from "@/lib/format";

export const mockClients: ClientRecord[] = [
  {
    id: "client-001",
    memberNo: "SBC-24001",
    fullName: "Mercy Wanjiru",
    phone: "+254 712 400 120",
    businessName: "Mercy Fresh Produce",
    county: "Nairobi",
    status: "active",
    savingsOnly: false,
    joinedAt: "2026-01-15T08:30:00.000Z",
  },
  {
    id: "client-002",
    memberNo: "SBC-24002",
    fullName: "Joseph Otieno",
    phone: "+254 733 188 502",
    businessName: "Otieno General Supplies",
    county: "Kisumu",
    status: "review",
    savingsOnly: false,
    joinedAt: "2026-02-11T10:10:00.000Z",
  },
  {
    id: "client-003",
    memberNo: "SBC-24003",
    fullName: "Ann Naliaka",
    phone: "+254 721 998 400",
    businessName: "Naliaka Salon",
    county: "Bungoma",
    status: "active",
    savingsOnly: true,
    joinedAt: "2026-03-01T06:45:00.000Z",
  },
  {
    id: "client-004",
    memberNo: "SBC-24004",
    fullName: "Peter Maina",
    phone: "+254 705 553 112",
    businessName: "Maina Auto Spares",
    county: "Kiambu",
    status: "inactive",
    savingsOnly: false,
    joinedAt: "2025-12-19T09:20:00.000Z",
  },
];

export const mockLoans: LoanRecord[] = [
  {
    id: "loan-001",
    clientId: "client-001",
    clientName: "Mercy Wanjiru",
    category: "Business",
    principal: 65000,
    balance: 18450,
    status: "active",
    repaymentFrequency: "weekly",
    repaymentPlan: "weekly",
    dueDate: "2026-06-19T00:00:00.000Z",
    termWeeks: 12,
    loanPeriodDays: 84,
    interestRate: 0.05,
    interestAmount: 3250,
    processingFee: 1000,
    insuranceFee: 500,
    penaltyRate: 0.02,
    totalDeductions: 4750,
    totalRepayment: 69750,
    netDisbursed: 60000,
    fundsTransferFee: 50,
    dailyContribution: 0,
    savingsAmount: 0,
    collateralJointFee: 0,
    unpaidShares: 0,
    unpaidSavings: 0,
    workflowStatus: "disbursed",
    paymentBreakdowns: [],
  },
  {
    id: "loan-002",
    clientId: "client-002",
    clientName: "Joseph Otieno",
    category: "Agriculture",
    principal: 120000,
    balance: 120000,
    status: "approved",
    repaymentFrequency: "daily",
    repaymentPlan: "daily",
    dueDate: "2026-07-03T00:00:00.000Z",
    termWeeks: 16,
    loanPeriodDays: 112,
    interestRate: 0.04,
    interestAmount: 4800,
    processingFee: 2000,
    insuranceFee: 1000,
    penaltyRate: 0.02,
    totalDeductions: 7800,
    totalRepayment: 127800,
    netDisbursed: 115000,
    fundsTransferFee: 100,
    dailyContribution: 0,
    savingsAmount: 0,
    collateralJointFee: 0,
    unpaidShares: 0,
    unpaidSavings: 0,
    workflowStatus: "disbursed",
    paymentBreakdowns: [],
  },
  {
    id: "loan-003",
    clientId: "client-004",
    clientName: "Peter Maina",
    category: "Other",
    principal: 45000,
    balance: 9800,
    status: "defaulted",
    repaymentFrequency: "weekly",
    repaymentPlan: "weekly",
    dueDate: "2026-04-20T00:00:00.000Z",
    termWeeks: 12,
    loanPeriodDays: 84,
    interestRate: 0.05,
    interestAmount: 2250,
    processingFee: 500,
    insuranceFee: 300,
    penaltyRate: 0.02,
    totalDeductions: 3050,
    totalRepayment: 48050,
    netDisbursed: 42000,
    fundsTransferFee: 30,
    dailyContribution: 0,
    savingsAmount: 0,
    collateralJointFee: 0,
    unpaidShares: 0,
    unpaidSavings: 0,
    workflowStatus: "disbursed",
    paymentBreakdowns: [],
  },
];

export const mockSavings: SavingsRecord[] = [
  {
    id: "sav-001",
    clientId: "client-001",
    clientName: "Mercy Wanjiru",
    mandatory: 4400,
    mandatoryShares: 6800,
    multiplier: 2200,
    withdrawable: 1200,
    total: 14600,
    updatedAt: "2026-05-10T14:20:00.000Z",
  },
  {
    id: "sav-002",
    clientId: "client-002",
    clientName: "Joseph Otieno",
    mandatory: 3000,
    mandatoryShares: 5000,
    multiplier: 4200,
    withdrawable: 0,
    total: 12200,
    updatedAt: "2026-05-09T11:00:00.000Z",
  },
  {
    id: "sav-003",
    clientId: "client-003",
    clientName: "Ann Naliaka",
    mandatory: 5200,
    mandatoryShares: 5400,
    multiplier: 1100,
    withdrawable: 450,
    total: 12150,
    updatedAt: "2026-05-11T06:55:00.000Z",
  },
];

export const mockTransactions: TransactionRecord[] = [
  {
    id: "txn-001",
    source: "mpesa",
    clientName: "Mercy Wanjiru",
    amount: 3200,
    method: "M-PESA Paybill",
    reference: "SIH9K2Q8X1",
    recordedAt: "2026-05-11T08:14:00.000Z",
    notes: "Loan repayment plus savings split",
    type: "payment",
  },
  {
    id: "txn-002",
    source: "legacy",
    clientName: "Joseph Otieno",
    amount: 1500,
    method: "Legacy sync",
    reference: "LEGACY-CONTRIB-289",
    recordedAt: "2026-05-10T17:40:00.000Z",
    notes: "Recovered from old contribution history",
    type: "deposit",
  },
  {
    id: "txn-003",
    source: "live",
    clientName: "Ann Naliaka",
    amount: 900,
    method: "Cash",
    reference: "RCPT-240511-009",
    recordedAt: "2026-05-10T12:20:00.000Z",
    notes: "Savings-only member contribution",
    type: "deposit",
  },
];

export const mockDashboard: DashboardSnapshot = {
  metrics: [
    {
      label: "Clients on Book",
      value: formatCompactNumber(412),
      helper: "388 active members across counties",
      tone: "emerald",
    },
    {
      label: "Live Portfolio",
      value: formatCurrency(8420000),
      helper: "Active and approved loans",
      tone: "blue",
    },
    {
      label: "Held Savings",
      value: formatCurrency(2310000),
      helper: "Mandatory, shares, multiplier, withdrawable",
      tone: "amber",
    },
    {
      label: "Watch List",
      value: "17",
      helper: "Overdue loans or pending visits",
      tone: "rose",
    },
  ],
  alerts: [
    "M-PESA callback endpoint is scaffolded and waiting for live Daraja credentials.",
    "Legacy transaction sync tables are included in the Supabase schema for phased migration.",
    "Savings portfolio logic now has dedicated tables for multiplier transfers and purpose-pool allocations.",
  ],
  clients: mockClients,
  loans: mockLoans,
  recentTransactions: mockTransactions,
  pendingActions: [
    {
      label: "Review overdue loans",
      href: "/loans?status=active&view=overdue",
      icon: "AlertCircle",
      badge: "17",
    },
    {
      label: "Process pending approvals",
      href: "/loans?status=pending",
      icon: "Clock",
      badge: "8",
    },
    {
      label: "Conduct field visits",
      href: "/clients?view=to_visit",
      icon: "MapPin",
      badge: "23",
    },
    {
      label: "Sync legacy transactions",
      href: "/sync",
      icon: "RefreshCw",
    },
  ],
};

export const mockReports: ReportsSnapshot = {
  activePortfolio: 8420000,
  memberSavings: 2310000,
  purposePool: 386400,
  collectionToday: 118500,
  totalDisbursed: 12800000,
  totalRepaid: 9350000,
  loanBreakdown: {
    active: 156,
    approved: 24,
    pending: 38,
    defaulted: 17,
    rejected: 12,
    completed: 89,
  },
  savingsBreakdown: {
    mandatory: 890000,
    shares: 1150000,
    multiplier: 210000,
    withdrawable: 60000,
  },
  topClients: [
    { name: "Sarah Wambui", totalLoans: 350000, outstanding: 180000 },
    { name: "David Mutua", totalLoans: 280000, outstanding: 145000 },
    { name: "Faith Achieng", totalLoans: 220000, outstanding: 95000 },
    { name: "James Mwangi", totalLoans: 180000, outstanding: 75000 },
    { name: "Esther Njeri", totalLoans: 150000, outstanding: 60000 },
  ],
};

export const mockSync: SyncSnapshot = {
  lastSyncLabel: "Legacy contribution replay completed 34 minutes ago",
  pendingCallbacks: 0,
  processedCallbacks: 12,
  runs: [
    {
      id: "sync-001",
      jobName: "legacy_transaction_sync",
      mode: "incremental",
      status: "completed",
      startedAt: "2026-05-11T07:42:00.000Z",
      finishedAt: "2026-05-11T07:49:00.000Z",
      details: "Imported 19 transactions and updated 7 client balances.",
    },
    {
      id: "sync-002",
      jobName: "client_refresh",
      mode: "full",
      status: "completed",
      startedAt: "2026-05-10T20:02:00.000Z",
      finishedAt: "2026-05-10T20:09:00.000Z",
      details: "Refreshed profile fields from the legacy member list.",
    },
    {
      id: "sync-003",
      jobName: "mpesa_callback_ingest",
      mode: "callback",
      status: "queued",
      startedAt: "2026-05-11T08:14:00.000Z",
      finishedAt: null,
      details: "Awaiting live callback once Daraja credentials are supplied.",
    },
  ],
};

export const mockSettings: SettingsSnapshot = {
  appName: "Sauti Business Community",
  deploymentMode: "Modern Next.js + Supabase rollout",
  supabaseReady: false,
  mpesaReady: false,
  dbSchemaReady: false,
  nextSteps: [
    "Paste database/fullupdate.sql into the Supabase SQL editor.",
    "Add Supabase project keys into .env.local.",
    "Share Daraja credentials so the callback and transaction readers can be wired live.",
  ],
};
